"""Generate the three deliverable notebooks as valid .ipynb JSON.

Run once: `python scripts/_gen_notebooks.py`. Kept in the repo so the notebooks
are reproducible/diff-able rather than hand-edited binary-ish JSON.

All three notebooks open with the same idempotent SETUP cell: on Colab/Kaggle it
clones the repo and `chdir`s into it; locally (run from the repo root) it is a
no-op. After SETUP, every path is repo-root-relative and `import src...` works.
"""
import json, os

NB_DIR = os.path.join(os.path.dirname(__file__), "..", "notebooks")
os.makedirs(NB_DIR, exist_ok=True)

REPO_URL = "https://github.com/Shiverion/text2sql-finetuning.git"
REPO_DIR = "text2sql-finetuning"

# Shared, environment-agnostic setup. Uses os.chdir (not the %cd magic) so it is
# valid inside the if-block and changes the *kernel* working directory.
SETUP = [
    "# --- SETUP: run me first (works on Colab, Kaggle AND locally) ---",
    "import os, sys, subprocess",
    "if not os.path.exists('src') and os.path.basename(os.getcwd()) != '{d}':".format(d=REPO_DIR),
    "    if not os.path.isdir('{d}'):".format(d=REPO_DIR),
    "        subprocess.run(['git', 'clone', '{url}'], check=True)".format(url=REPO_URL),
    "    os.chdir('{d}')".format(d=REPO_DIR),
    "sys.path.insert(0, os.getcwd())",
    "print('working dir :', os.getcwd())",
    "print('src present :', os.path.isdir('src'))",
]


def md(*lines):
    return {"cell_type": "markdown", "metadata": {}, "source": _src(lines)}


def code(*lines):
    return {"cell_type": "code", "metadata": {}, "execution_count": None,
            "outputs": [], "source": _src(lines)}


def _src(lines):
    text = "\n".join(lines)
    parts = text.split("\n")
    return [p + "\n" for p in parts[:-1]] + [parts[-1]]


def notebook(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
            "colab": {"provenance": []},
            "accelerator": "GPU",
        },
        "nbformat": 4, "nbformat_minor": 5,
    }


def write(name, cells):
    path = os.path.join(NB_DIR, name)
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(notebook(cells), fh, indent=1)
    print("wrote", os.path.normpath(path))


# ===================================================================== #
# 01 — Data exploration
# ===================================================================== #
nb1 = [
 md("# 01 · Dataset Exploration — BIRD & SynSQL-2.5M",
    "",
    "Goal: understand the data **before** training — size, difficulty mix, SQL",
    "complexity, schema breadth — so the fine-tuning recipe is grounded in",
    "evidence rather than guesswork.",
    "",
    "Runs on CPU. If the official BIRD files aren't present it falls back to the",
    "bundled synthetic `data/sample/` so the notebook always executes."),
 code(*SETUP),
 code("!pip install -q datasets pandas matplotlib"),
 code("import os, json, glob, re",
      "import pandas as pd",
      "import matplotlib.pyplot as plt",
      "FIG = 'report/figures'; os.makedirs(FIG, exist_ok=True)"),
 md("## 1. Load BIRD train (or fall back to the sample)",
    "",
    "Official BIRD download (run on Colab if you want the full set):",
    "```bash",
    "!wget -q https://bird-bench.oss-cn-beijing.aliyuncs.com/train.zip && unzip -q train.zip",
    "!wget -q https://bird-bench.oss-cn-beijing.aliyuncs.com/dev.zip && unzip -q dev.zip",
    "```",
    "Links occasionally move — see https://bird-bench.github.io for the current ones,",
    "or use a 🤗 mirror such as `lamini/bird_text_to_sql`."),
 code("def load_examples():",
      "    for p in ['train/train.json', 'dev/dev.json', 'data/train.json']:",
      "        if os.path.exists(p):",
      "            print('using', p)",
      "            return json.load(open(p, encoding='utf-8')), p",
      "    print('BIRD not found - using bundled sample')",
      "    return json.load(open('data/sample/examples.json', encoding='utf-8')), 'sample'",
      "",
      "rows, source = load_examples()",
      "df = pd.DataFrame(rows)",
      "df['sql'] = df.get('SQL', df.get('sql'))",
      "print('examples:', len(df))",
      "df.head(3)"),
 md("## 2. Difficulty distribution",
    "BIRD labels each dev question simple / moderate / challenging. The mix tells",
    "us where accuracy will be hardest and how to read per-bucket EX later."),
 code("if 'difficulty' in df and df['difficulty'].notna().any():",
      "    vc = df['difficulty'].value_counts()",
      "    print(vc)",
      "    ax = vc.plot(kind='bar', title='Question difficulty', rot=0)",
      "    ax.figure.tight_layout(); ax.figure.savefig(f'{FIG}/difficulty.png', dpi=120)",
      "else:",
      "    print('no difficulty labels in this split')"),
 md("## 3. SQL complexity — length & keyword frequency",
    "Proxies for how hard generation is: long queries, JOINs, aggregation, nesting."),
 code("df['sql_len'] = df['sql'].str.len()",
      "df['n_tokens'] = df['sql'].str.split().apply(len)",
      "print(df[['sql_len','n_tokens']].describe())",
      "ax = df['n_tokens'].plot(kind='hist', bins=30, title='SQL length (tokens)')",
      "ax.figure.tight_layout(); ax.figure.savefig(f'{FIG}/sql_len.png', dpi=120)"),
 code("KEYWORDS = ['JOIN','LEFT JOIN','GROUP BY','ORDER BY','WHERE','HAVING',",
      "            'DISTINCT','LIMIT','COUNT','SUM','AVG','MAX','MIN','CASE',",
      "            'SELECT.*SELECT']  # last = nested subquery (regex)",
      "up = df['sql'].str.upper()",
      "freq = {k: int(up.str.contains(k, regex=True).sum()) for k in KEYWORDS}",
      "freq = dict(sorted(freq.items(), key=lambda x: -x[1]))",
      "print(json.dumps(freq, indent=2))",
      "ax = pd.Series(freq).plot(kind='barh', title='SQL keyword frequency')",
      "ax.invert_yaxis(); ax.figure.tight_layout(); ax.figure.savefig(f'{FIG}/keywords.png', dpi=120)"),
 md("## 4. Schema breadth",
    "How many distinct databases, and how wide are they? Wide schemas are the",
    "main reason a small model fails: the relevant columns get lost in a long",
    "prompt. This motivates schema serialization choices in `src/schema_utils.py`."),
 code("if 'db_id' in df:",
      "    print('distinct databases:', df['db_id'].nunique())",
      "    print(df['db_id'].value_counts().head(10))"),
 code("# Column counts per DB. Sample DB by default; on full BIRD point the glob",
      "# at dev_databases/**/*.sqlite.",
      "import sqlite3",
      "dbs = glob.glob('data/sample/db/**/*.sqlite', recursive=True) or glob.glob('dev*/**/*.sqlite', recursive=True)",
      "for db in dbs[:10]:",
      "    con = sqlite3.connect(db)",
      "    tabs = [r[0] for r in con.execute(\"select name from sqlite_master where type='table'\")]",
      "    ncols = sum(len(con.execute(f'PRAGMA table_info(\"{t}\")').fetchall()) for t in tabs)",
      "    print(os.path.basename(db), '->', len(tabs), 'tables,', ncols, 'columns')",
      "    con.close()"),
 md("## 5. Takeaways → recipe",
    "",
    "- **Schema is the prompt's bulk** → serialize compactly; keep `max_seq_length`",
    "  large enough (2048) to fit the biggest schemas without truncation.",
    "- **Evidence/hints matter** (BIRD) → always include them in the prompt.",
    "- **JOIN + GROUP BY dominate** → these are the patterns LoRA must learn; the",
    "  fintech use-case ('top merchants last quarter') is exactly this shape.",
    "- **Difficulty is skewed to simple/moderate** → expect most EX gains there;",
    "  challenging (nested, multi-join) will lag — call this out in the report."),
]

# ===================================================================== #
# 02 — Fine-tuning (Colab / Kaggle, storage-lean)
# ===================================================================== #
nb2 = [
 md("# 02 · Fine-tune Qwen2.5-Coder (QLoRA) for Text2SQL — Colab T4 / Kaggle",
    "",
    "Free-tier recipe: **Unsloth + QLoRA** on `Qwen2.5-Coder-1.5B-Instruct`",
    "(Apache-2.0, 1.54B params). Designed to fit **Kaggle's 19 GB** working disk.",
    "",
    "**Key storage trick:** training never executes SQL, so it only needs the",
    "*schema text* — we build that from BIRD's small `train_tables.json` and **skip",
    "the ~8 GB `train_databases` download entirely**. Only the ~1.3 GB",
    "`dev_databases` is fetched, for execution-accuracy eval.",
    "",
    "> **Colab:** Runtime → Change runtime type → **T4 GPU**.  ",
    "> **Kaggle:** Settings → Accelerator → **GPU T4 x2** (or **GPU P100**), and **Internet → On**.  ",
    "> Then run all cells.",
    "",
    "⚠️ **Use a GPU, not TPU.** Unsloth + QLoRA + bitsandbytes are CUDA-only and will",
    "fail on a TPU runtime. Training uses a **single GPU** — with *T4 x2* the second",
    "T4 stays idle, which is normal and fine for a 1.5B QLoRA (no multi-GPU needed).",
    "",
    "⏱️ **Rough timing on one T4:** download+preprocess ≈ 3–5 min (range fetch),",
    "model download ≈ 1 min, training ≈ **~2.5 h** for `8000 samples × 2 epochs`",
    "(~900 steps). Want it fast? See the quick-run option in step 5 (~30–45 min)."),
 code("import torch; print('CUDA:', torch.cuda.is_available(),",
      "      torch.cuda.get_device_name(0) if torch.cuda.is_available() else '(enable the GPU runtime!)')"),
 md("## 1. Get the code (clone the repo)"),
 code(*SETUP),
 md("## 2. Install Unsloth + training stack",
    "`pip install unsloth` pulls a torch/transformers/trl/peft combo tested",
    "together — don't hand-pin these unless you know why. (~2–4 min.)"),
 code("!pip install -q unsloth",
      "# If you hit a version error later, get the matching nightly instead:",
      "# !pip install -q --upgrade --no-deps \"unsloth @ git+https://github.com/unslothai/unsloth.git\" \\",
      "#     \"unsloth_zoo @ git+https://github.com/unslothai/unsloth_zoo.git\""),
 md("## 3. Download BIRD — fast & storage-lean (fits 19 GB)",
    "Training only needs schema *text*, so we grab just `train.json` +",
    "`train_tables.json` straight out of the 8.3 GB remote zip via **HTTP range",
    "requests** (≈50 MB — no full download, takes seconds instead of ~20 min). Only",
    "`dev_databases` (~1.3 GB) is fetched whole, for execution eval. Every step",
    "prints progress + timing so you're never staring at a frozen cell."),
 code("!pip install -q remotezip"),
 code("import os, glob, time",
      "REPO = os.getcwd()",
      "BIRD = 'https://bird-bench.oss-cn-beijing.aliyuncs.com'",
      "",
      "# --- TRAIN: pull ONLY the 2 JSON files out of the remote 8.3 GB zip (range GET) ---",
      "if os.path.exists('train/train_tables.json'):",
      "    print('[train] schemas already present - skipping download')",
      "else:",
      "    print('[train] fetching train.json + train_tables.json via HTTP range '",
      "          '(NOT the 8 GB databases)...', flush=True)",
      "    t = time.time()",
      "    try:",
      "        from remotezip import RemoteZip",
      "        with RemoteZip(f'{BIRD}/train.zip') as rz:",
      "            for m in ['train/train.json', 'train/train_tables.json']:",
      "                print('   downloading', m, '...', flush=True)",
      "                rz.extract(m, REPO)",
      "        print(f'   OK in {time.time()-t:.0f}s', flush=True)",
      "    except Exception as e:",
      "        print('   range fetch failed (%s) -> full-download fallback' % e, flush=True)",
      "        !wget --progress=dot:giga -c {BIRD}/train.zip -O /tmp/train.zip",
      "        !unzip -o /tmp/train.zip 'train/train.json' 'train/train_tables.json' -d {REPO}",
      "        !rm -f /tmp/train.zip"),
 code("# --- DEV: need the real .sqlite for execution eval (~330 MB zip) ---",
      "if glob.glob('dev*/dev.json'):",
      "    print('[dev] already present - skipping download')",
      "else:",
      "    print('[dev] downloading dev.zip (~330 MB) - progress dots below...', flush=True)",
      "    !wget --progress=dot:giga -c {BIRD}/dev.zip -O /tmp/dev.zip",
      "    print('[dev] extracting...', flush=True)",
      "    !unzip -o -q /tmp/dev.zip -d {REPO}",
      "    !rm -f /tmp/dev.zip",
      "for z in glob.glob('dev*/dev_databases.zip'):   # un-nest the dev databases",
      "    print('[dev] un-nesting', z, '...', flush=True)",
      "    !unzip -o -q '{z}' -d '{os.path.dirname(z)}'",
      "    !rm -f '{z}'",
      "print('--- disk usage ---', flush=True)",
      "!du -sh train dev* 2>/dev/null; df -h {REPO} | tail -1"),
 md("### Resolve paths",
    "Auto-detects the dev folder name (BIRD has shipped it as `dev/` and",
    "`dev_20240627/` in different releases)."),
 code("TRAIN_JSON   = 'train/train.json'",
      "TRAIN_TABLES = 'train/train_tables.json'   # schemas WITHOUT databases",
      "dev_jsons = glob.glob('dev*/dev.json')",
      "DEV_DIR  = os.path.dirname(dev_jsons[0]) if dev_jsons else 'dev'",
      "DEV_JSON = f'{DEV_DIR}/dev.json'",
      "DEV_DB   = f'{DEV_DIR}/dev_databases'      # real .sqlite for execution eval",
      "print('train :', TRAIN_JSON, '+', TRAIN_TABLES)",
      "print('dev   :', DEV_JSON, '| db_root:', DEV_DB, '| exists:', os.path.isdir(DEV_DB))"),
 md("## 4. Preprocess → JSONL",
    "Train uses `--tables_json` (schemas, no databases). Dev uses `--db_root` so",
    "the predicted SQL can later be executed against the real databases."),
 code("!python -m src.data_prep --source bird --json {TRAIN_JSON} --tables_json {TRAIN_TABLES} \\",
      "    --out data/processed/bird_train.jsonl --shuffle",
      "!python -m src.data_prep --source bird --json {DEV_JSON} --db_root {DEV_DB} \\",
      "    --out data/processed/bird_dev.jsonl"),
 code("# sanity: both files should be non-empty (dev > 0 confirms the DBs extracted)",
      "import json",
      "for f in ['data/processed/bird_train.jsonl', 'data/processed/bird_dev.jsonl']:",
      "    n = sum(1 for _ in open(f, encoding='utf-8'))",
      "    print(f'{f}: {n} records')",
      "print()",
      "print(json.dumps(json.loads(open('data/processed/bird_train.jsonl').readline()), indent=2)[:1000])"),
 md("## 5. Train (QLoRA)",
    "Runs the hardened trainer in `src/train.py` (Unsloth + completion-only loss;",
    "SFTConfig/SFTTrainer kwargs auto-adapt to the installed TRL version). The",
    "trainer logs `loss` every 20 steps, so you'll see live progress.",
    "",
    "Pick a run size:",
    "- **Full** `--max_train_samples 8000 --epochs 2` → ~900 steps → **~2.5 h** (best quality).",
    "- **Quick** `--max_train_samples 3000 --epochs 1` → ~190 steps → **~30–45 min** (good enough for the brief).",
    "- **Smoke** `--max_steps 60` → a few minutes, just to confirm it runs.",
    "",
    "Edit the flags in the cell below to choose. Default is the quick run."),
 code("!python -m src.train --preset exp1_qwen1.5b_bird_qlora \\",
      "    --train_file data/processed/bird_train.jsonl \\",
      "    --val_file   data/processed/bird_dev.jsonl \\",
      "    --max_train_samples 3000 --epochs 1   # full run: --max_train_samples 8000 --epochs 2"),
 md("Adapter + tokenizer are saved to `outputs/qwen2.5-coder-1.5b-bird-qlora/`",
    "(a few MB — well within 19 GB). Implementation: [`src/train.py`](src/train.py);",
    "hyper-parameters: the presets in [`src/config.py`](src/config.py)."),
 md("## 6. (Optional) push the adapter to the Hugging Face Hub",
    "Set an `HF_TOKEN` secret first — **Kaggle:** Add-ons → Secrets → `HF_TOKEN`;",
    "**Colab:** key icon → `HF_TOKEN`."),
 code("import os",
      "from huggingface_hub import HfApi, login",
      "ADAPTER_DIR = 'outputs/qwen2.5-coder-1.5b-bird-qlora'",
      "HF_REPO     = 'Shiverion/qwen2.5-coder-1.5b-bird-qlora'  # <- change to your username",
      "",
      "token = os.environ.get('HF_TOKEN')",
      "if token is None:",
      "    try:",
      "        from kaggle_secrets import UserSecretsClient",
      "        token = UserSecretsClient().get_secret('HF_TOKEN')",
      "    except Exception: pass",
      "if token is None:",
      "    try:",
      "        from google.colab import userdata",
      "        token = userdata.get('HF_TOKEN')",
      "    except Exception: pass",
      "",
      "if token and os.path.isdir(ADAPTER_DIR):",
      "    login(token=token)",
      "    api = HfApi(); api.create_repo(HF_REPO, repo_type='model', exist_ok=True)",
      "    api.upload_folder(folder_path=ADAPTER_DIR, repo_id=HF_REPO, repo_type='model')",
      "    print('pushed ->', f'https://huggingface.co/{HF_REPO}')",
      "else:",
      "    print('skipped: set the HF_TOKEN secret and make sure', ADAPTER_DIR, 'exists')"),
 md("Now run **03_inference_eval.ipynb** (same session) to measure execution accuracy."),
]

# ===================================================================== #
# 03 — Inference + evaluation
# ===================================================================== #
nb3 = [
 md("# 03 · Inference & Execution-Accuracy Evaluation",
    "",
    "Generate SQL on BIRD dev with the fine-tuned adapter, then score with",
    "execution accuracy (EX), valid-SQL rate and exact match — plus a baseline",
    "(same model, no fine-tuning) for a clean before/after comparison.",
    "",
    "**Self-sufficient:** runs in a *fresh* session — it pulls the fine-tuned",
    "adapter from the **Hugging Face Hub** and rebuilds the dev set if needed. (If",
    "you're in the same session as notebook 02, it reuses what's already there.)"),
 code(*SETUP),
 code("!pip install -q unsloth   # needed for inference if this is a fresh session"),
 md("## 1. Choose the fine-tuned model",
    "Defaults to your HF adapter repo (works in any session). If you're in the same",
    "session as notebook 02, you can point this at the local `outputs/...` folder."),
 code("FT_MODEL = 'Shiverion/qwen2.5-coder-1.5b-bird-qlora'   # <- your HF repo from notebook 02",
      "# FT_MODEL = 'outputs/qwen2.5-coder-1.5b-bird-qlora'   # use this if same session as nb 02",
      "BASE_MODEL = 'unsloth/Qwen2.5-Coder-1.5B-Instruct'",
      "print('fine-tuned :', FT_MODEL)"),
 md("## 2. Prepare the dev set (idempotent)",
    "Downloads + preprocesses BIRD dev only if `bird_dev.jsonl` isn't already here.",
    "The real `.sqlite` databases are required to *execute* the predicted queries."),
 code("import os, glob",
      "REPO = os.getcwd(); BIRD = 'https://bird-bench.oss-cn-beijing.aliyuncs.com'",
      "dev_jsonl = 'data/processed/bird_dev.jsonl'",
      "if os.path.exists(dev_jsonl) and os.path.getsize(dev_jsonl) > 0:",
      "    print('dev set already prepared:', dev_jsonl)",
      "else:",
      "    if not glob.glob('dev*/dev.json'):",
      "        print('downloading dev.zip (~330 MB)...', flush=True)",
      "        !wget --progress=dot:giga -c {BIRD}/dev.zip -O /tmp/dev.zip",
      "        !unzip -o -q /tmp/dev.zip -d {REPO}",
      "        !rm -f /tmp/dev.zip",
      "    for z in glob.glob('dev*/dev_databases.zip'):",
      "        print('un-nesting', z, '...', flush=True)",
      "        !unzip -o -q '{z}' -d '{os.path.dirname(z)}'",
      "        !rm -f '{z}'",
      "    dj = glob.glob('dev*/dev.json')[0]; dd = os.path.dirname(dj) + '/dev_databases'",
      "    !python -m src.data_prep --source bird --json {dj} --db_root {dd} --out {dev_jsonl}",
      "n = sum(1 for _ in open(dev_jsonl, encoding='utf-8'))",
      "print(f'{dev_jsonl}: {n} records (must be > 0 for execution eval)')"),
 md("## 3. Baseline — base model, zero-shot",
    "Establishes the lift attributable to fine-tuning. (`--limit 200` keeps it",
    "quick; remove for the full dev set.)"),
 code("!python -m src.inference --model_dir {BASE_MODEL} \\",
      "    --input data/processed/bird_dev.jsonl --output outputs/preds_base.jsonl --limit 200",
      "!python -m src.evaluate --pred outputs/preds_base.jsonl --report outputs/metrics_base.json"),
 md("## 4. Fine-tuned model (from Hugging Face)",
    "`src.inference` loads the adapter and its base model automatically (Unsloth",
    "reads `base_model_name_or_path` from the adapter config)."),
 code("!python -m src.inference --model_dir {FT_MODEL} \\",
      "    --input data/processed/bird_dev.jsonl --output outputs/preds_ft.jsonl --limit 200",
      "!python -m src.evaluate --pred outputs/preds_ft.jsonl --report outputs/metrics_ft.json"),
 md("## 5. Compare"),
 code("import json, pandas as pd, os",
      "os.makedirs('report/figures', exist_ok=True)",
      "base = json.load(open('outputs/metrics_base.json'))",
      "ft   = json.load(open('outputs/metrics_ft.json'))",
      "tbl = pd.DataFrame({'baseline': base, 'fine-tuned': ft}).loc[",
      "    ['execution_accuracy','valid_sql_rate','exact_match']]",
      "print(tbl)",
      "ax = tbl.plot(kind='bar', rot=0, title='Baseline vs fine-tuned'); ax.figure.tight_layout()",
      "ax.figure.savefig('report/figures/before_after.png', dpi=120)"),
 md("## 6. Error analysis",
    "Read the captured failures to find systematic mistakes (hallucinated columns,",
    "wrong joins, missing GROUP BY). This is what drives the next experiment."),
 code("for e in ft.get('error_samples', [])[:10]:",
      "    print(e['type'])",
      "    print('  pred:', e.get('pred',''))",
      "    if 'error' in e: print('  err :', e['error'])",
      "    print()"),
 md("## 7. Try the motivating question live",
    "Uses the bundled fintech DB, so it works even without BIRD downloaded."),
 code("from src.inference import load_model, generate_batch",
      "from src.prompts import build_messages, extract_sql",
      "from src.schema_utils import serialize_schema",
      "model, tok, _ = load_model(FT_MODEL, 2048, load_in_4bit=True)",
      "tok.padding_side='left'; tok.pad_token = tok.pad_token or tok.eos_token",
      "schema = serialize_schema('data/sample/db/fintech/fintech.sqlite')",
      "q = 'Who were the top performing merchants last quarter?'",
      "prompt = tok.apply_chat_template(build_messages(schema, q), tokenize=False, add_generation_prompt=True)",
      "print(extract_sql(generate_batch(model, tok, [prompt], 256)[0]))"),
]

write("01_data_exploration.ipynb", nb1)
write("02_finetune_qlora.ipynb", nb2)
write("03_inference_eval.ipynb", nb3)
print("done")
